version: '3.8'

services:
  db:
    image: mariadb:10.11
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_AUTO_UPGRADE=1
    secrets:
      - db_root_password
      - db_password
    networks:
      - app_internal
    volumes:
      - ${DATA_ROOT}/mariadb-data:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager # DB should be pinned to a stable stateful node

networks:
  app_internal:
    external: true

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_password:
    file: ./secrets/db_password.txt
